# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c623c7dc3743aaf049398f0718d7c9d9720897b9b15ef274d8fba75e555bfc4255895c49470006a11d2980dea911a388d9adf705f259e0cd3fe45f11f6a3baa5

test:
  secret_key_base: 314ec8bd86cbae03be4a119ce94e588bd9174d92d6f557c8fcc3f657c39a7229a1edd2beafdde4cf15efc226c59fcbecdaab9fd325b2c8f4c46bca9ad6dbffaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
